const constants = {
    ADD_DRINK: "ADD_DRINK",
    REMOVE_DRINK: "REMOVE_DRINK",

    GET_DRINK_DETAILS: "GET_DRINK_DETAILS",

    FLAG_DRINK: "FLAG_DRINK",
    INCREMENT_DRINK: "INCREMENT_DRINK",
    DECREMENT_DRINK: "DECREMENT_DRINK",

    GET_ALL_DRINKS: "GET_ALL_DRINKS",

    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",

    GET_DRINK_SUGGESTIONS: "GET_SUGGESTIONS",
    CLEAR_DRINK_SUGGESTIONS: "CLEAR_SUGGESTIONS",

    GET_BAR_SUGGESTIONS: "GET_BAR_SUGGESTIONS",
    CLEAR_BAR_SUGGESTIONS: "CLEAR_BAR_SUGGESTIONS",
}

export default constants