const constants = {
    ADD_DRINK: "ADD_DRINK",
    REMOVE_DRINK: "REMOVE_DRINK",

    GET_DRINK_DETAILS: "GET_DRINK_DETAILS",

    FLAG_UNAVAILABLE: "FLAG_UNAVAILABLE",
    REMOVE_FLAG_UNAVAILABLE: "REMOVE_FLAG_UNAVAILABLE",
    FLAG_PRICE: "FLAG_PRICE",
    REMOVE_FLAG_PRICE: "REMOVE_FLAG_PRICE",

    INCREMENT_DRINK: "INCREMENT_DRINK",
    DECREMENT_DRINK: "DECREMENT_DRINK",

    GET_ALL_DRINKS: "GET_ALL_DRINKS",

    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",

    FETCH_DRINK_SUGGESTIONS: "FETCH_DRINK_SUGGESTIONS",
    CLEAR_DRINK_SUGGESTIONS: "CLEAR_DRINK_SUGGESTIONS",
    CHANGE_DRINK_SUGGESTIONS: "CHANGE_DRINK_SUGGESTIONS",
    CANCEL_FETCHING_DRINK_SUGGESTIONS: "CANCEL_FETCHING_DRINK_SUGGESTIONS",

    FETCH_BAR_SUGGESTIONS: "FETCH_BAR_SUGGESTIONS",
    CLEAR_BAR_SUGGESTIONS: "CLEAR_BAR_SUGGESTIONS",
    CHANGE_BAR_SUGGESTION: "CHANGE_BAR_SUGGESTION",
    CANCEL_FETCHING_BAR_SUGGESTIONS: "CANCEL_FETCHING_BAR_SUGGESTIONS",
};

export default constants;